create table public.activities (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Donjon', 'Quête', 'Succès', 'Drop', 'XP', 'Event')),
  nom text not null check (char_length(trim(nom)) between 1 and 100),
  niveau integer not null check (niveau between 1 and 200),
  description text not null default '' check (char_length(description) <= 500),
  organisateur_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
create policy "Les membres peuvent voir les profils publics"
on public.profiles for select to authenticated using (true);

alter table public.activities enable row level security;
create policy "Les membres peuvent voir les activités"
on public.activities for select to authenticated using (true);
create policy "Un membre peut créer ses activités"
on public.activities for insert to authenticated
with check (auth.uid() = organisateur_id);
create policy "Un organisateur peut modifier son activité"
on public.activities for update to authenticated
using (auth.uid() = organisateur_id)
with check (auth.uid() = organisateur_id);
create policy "Un organisateur peut supprimer son activité"
on public.activities for delete to authenticated
using (auth.uid() = organisateur_id);

create or replace function public.limiter_activites_par_membre()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  nombre_activites integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(new.organisateur_id::text, 0));

  select count(*) into nombre_activites
  from public.activities
  where organisateur_id = new.organisateur_id
    and (tg_op = 'INSERT' or id <> new.id);

  if nombre_activites >= 2 then
    raise exception 'ACTIVITES_LIMIT_REACHED';
  end if;

  return new;
end;
$$;

create trigger verifier_limite_activites
before insert or update of organisateur_id on public.activities
for each row execute procedure public.limiter_activites_par_membre();
