const listeDonjons = [
	"Crypte de Kardorim",
	"Grange du Tournesol Affamé",
	"Château Ensablé",
	"Cour du Bouftou Royal",
	"Cache de Kankreblath",
	"Maison Fantôme",
	"Donjon des Scarafeuilles",
	"Donjon des Squelettes",
	"Donjon des Tofus",
	"Akadémie des Gobs",
	"Donjon des Bworks",
	"Donjon des Forgerons",
	"Grotte Hesque",
	"Donjon des Larves",
	"Nid du Kwakwa",
	"Refuge Sylvestre",
	"Château du Wa Wabbit",
	"Clos des Blops",
	"Gelaxième Dimension",
	"Village Kanniboul",
	"Fonderie des Waddicts",
	"Cale de l'Arche d'Otomaï",
	"Laboratoire de Brumen Tinctorias",
	"Pitons Rocheux des Craqueleurs",
	"Épreuve de Draegnerys",
	"Terrier du Wa Wabbit",
	"Cimetière des mastodontes",
	"Chapiteau des Magik Riktus",
	"Domaine Ancestral",
	"Antre de la Reine Nyée",
	"Bateau du Chouque",
	"Antre du Dragon Cochon",
	"Caverne du Koulosse",
	"Tanière du Meulou",
	"Arbre de Moon",
	"Fabrique de Malléfisk",
	"Théâtre de Dramak",
	"Repaire du Kharnozor",
	"Bibliothèque du Maître Corbac",
	"Goulet du Rasboul",
	"Miausolée du Pounicheur",
	"Bambusaie de Damadrya",
	"Garde-manger du Rat Blanc",
	"Sousouricière du Rat Noir",
	"Antre du Blop Multicolore Royal",
	"Centre du Labyrinthe du Minotoror",
	"Serre du Royalmouth",
	"Tofulailler Royal",
	"Antre de Crocabulia",
	"Repaire de Skeunk",
	"Mégalithe de Fraktale",
	"Ring du Capitaine Ekarlatte",
	"Caverne d'El Piko",
	"Volière de la Haute Truche",
	"Atelier du Tanukouï San",
	"Vallée de la Dame des eaux",
	"Croquanterie",
	"Clairière du Chêne Mou",
	"Laboratoire du Tynril",
	"Excavation du Mansot Royal",
	"Dojo du Vent",
	"Fabrique de foux d'artifice",
	"Épave du Grolandais violent",
	"Repaire de Sphincter Cell",
	"Galerie du Phossile",
	"Tertre du long sommeil",
	"Canopée du Kimbo",
	"Salle du Minotot",
	"Hypogée de l'Obsidiantre",
	"Grotte de Kanigroula",
	"Plateau de Ush",
	"Tombe du Shogun Tofugawa",
	"Horologium de XLII",
	"Tanière Givrefoux",
	"Demeure des Esprits",
	"Boyau du Père Ver",
	"Poste de contrôle du Supervizœuf",
	"Antre du Korriandre",
	"Antre du Kralamoure Géant",
	"Grotte du Bworker",
	"Temple du Grand Ougah",
	"Cave du Toxoliath",
	"Antichambre des Gloursons",
	"Cavernes du Kolosso",
	"Mine de Sakaï",
	"Pyramide d'Ombre",
	"Camp du Comte Razof",
	"Bastion des Marteaux-Aigris",
	"Aquadôme de Merkator",
	"Donjon du Comte Harebourg",
	"Forgefroide de Missiz Frizz",
	"Laboratoire de Nileza",
	"Salons privés de Klime",
	"Transporteur de Sylargh",
	"Œil de Vortex",
	"Palais du roi Nidas",
	"Trône de la Cour Sombre",
	"Défi du Chalœil",
	"Temple de Koutoulou",
	"Vaisseau du Capitaine Meno",
	"Palais de Dantinéa",
	"Belvédère d'Ilyzaelle",
	"Tour de Solar",
	"Tour de Bethel",
	"Brasserie du roi Dazak",
	"Chambre de Tal Kasha",
	"Sanctuaire de Torkélonia",
	"Manoir des Katrepat",
	"Sentence de la Balance",
	"Fers de la Tyrannie",
	"Trône de sang",
	"Arbre de mort",
	"Souvenir d'Imagiro",
	"Mémoire d'Orukam",
	"Rituel de Kabahal",
	"Temple du dieu Kao",
	"Bataille de l'Aurore Pourpre",
	"Chambre des maléfices",
	"Caverne de Cire Momore",
	"Tempête de l'Éliocalypse",
	"Temple de Gargandyas",
	"Breuil du Vénérable",
	"Autel de la Déchireuse",
];
